from __future__ import annotations

"""Mini-experiment: Flash-Fusion scores across model sizes and datasets.

Runs FLASH_FUSION for the selected datasets and models, then computes accuracy
using the benchmark-style ground-truth LLM judge.
"""

"""
# For all the runs in case you're feeling lazy
python -m flashfusion.miniexp.modeltype \
  --run-all \
  --judge-model meta-llama/llama-3.3-70b-instruct

# Run 1
python -m flashfusion.miniexp.modeltype \
  --run-id 1 \
  --judge-model meta-llama/llama-3.3-70b-instruct \
  --plot

# Run 2
python -m flashfusion.miniexp.modeltype \
  --run-id 2 \
  --judge-model meta-llama/llama-3.3-70b-instruct \
  --plot

# Run 3
python -m flashfusion.miniexp.modeltype \
  --run-id 3 \
  --judge-model meta-llama/llama-3.3-70b-instruct \
  --plot

# Regenerate figure only from existing run data
python -m flashfusion.miniexp.modeltype \
  --plot-only \
  --output-dir flashfusion/miniexp/results/modeltype
"""

import argparse
import dataclasses
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import pandas as pd

# Ensure `flashfusion` is importable when run from subdirectories.
_script_dir = Path(__file__).resolve().parent
_repo_root = _script_dir.parents[1]
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from flashfusion.config import MODEL_RATE_PER_1M_TOKENS
from flashfusion.eval.ground_truth import load_ground_truth
from flashfusion.eval.ground_truth_llm_judge import run_llm_ground_truth_judge
from flashfusion.eval.metrics import aggregate_metrics
from flashfusion.eval.queries import SUPPORTED_DATASETS, get_queries
from flashfusion.pipeline.loader import load_dataset_by_name
from flashfusion.pipeline.runner import BaselineRunner, LLMClient, RunResult

DEFAULT_SMALL_MODELS: list[str] = [
    "google/gemma-4-31b-it",
    "qwen/qwen-2.5-7b-instruct",
]

DEFAULT_DATA_PATHS: dict[str, str] = {
    "wisdm": "data/AutoIOT_dataset/IMU/WISDM_ar_v1.1_raw.txt",
    "mit_ecg": "data/AutoIOT_dataset/ECG.0/MIT_arrythmia_v1.txt",
    "bus": "data/bus/bus_data.csv",
}

DEFAULT_GT_PATHS: dict[str, str] = {
    "wisdm": "flashfusion/eval/ground_truth/ground_truth_wisdm.json",
    "mit_ecg": "flashfusion/eval/ground_truth/ground_truth_mit_ecg.json",
    "bus": "flashfusion/eval/ground_truth/ground_truth_bus.json",
}

DEFAULT_OUTPUT_DIR = "flashfusion/miniexp/results/modeltype"
DEFAULT_JUDGE_MODEL = "meta-llama/llama-3.3-70b-instruct"

# Paths to pre-existing benchmark data generated by performance/measure.py.
# Flash-Fusion rows here correspond to llama-3.3-70b-versatile (3 genuine run_ids).
DEFAULT_BENCHMARK_ALL_ROOT = "flashfusion/performance/data/run_all_remaining_20260528_215519"
DEFAULT_BENCHMARK_ECG_ROOT = "flashfusion/performance/data/run_ecg_ff_20260529_115359"
BENCHMARK_MODEL = "meta-llama/llama-3.3-70b-versatile"

# Canonical bar ordering for the model-type plot (ascending model size).
MODEL_PLOT_ORDER: list[str] = [
    "qwen/qwen-2.5-7b-instruct",
    "google/gemma-4-31b-it",
    BENCHMARK_MODEL,
]

DATASET_ORDER: list[str] = ["bus", "wisdm", "mit_ecg"]
DATASET_LABELS: dict[str, str] = {
    "bus": "Bus",
    "wisdm": "WISDM",
    "mit_ecg": "ECG",
}
FONT_SCALE = 1.25
PLOT_RC = {
    "font.family": "DejaVu Sans",
    "font.size": 11 * FONT_SCALE,
    "axes.labelsize": 11 * FONT_SCALE,
    "axes.labelweight": "bold",
    "xtick.labelsize": 10 * FONT_SCALE,
    "ytick.labelsize": 10 * FONT_SCALE,
    "legend.fontsize": 12 * FONT_SCALE,
    "legend.title_fontsize": 12 * FONT_SCALE,
}


def _is_forbidden_chat_data_path(path: str) -> bool:
    normalized = os.path.normpath(path).replace("\\", "/")
    if normalized == "chat/data" or normalized.startswith("chat/data/"):
        return True
    return "/chat/data/" in normalized


def _resolve_dataset_file(dataset: str, data_path: str | None) -> Path:
    raw = data_path or DEFAULT_DATA_PATHS[dataset]
    if _is_forbidden_chat_data_path(raw):
        raise ValueError(f"Path {raw!r} is under chat/data, which is not allowed.")

    p = Path(raw)
    if not p.is_absolute():
        p = (_repo_root / p).resolve()

    if p.is_dir():
        suffix = {
            "wisdm": "WISDM_ar_v1.1_raw.txt",
            "mit_ecg": "MIT_arrythmia_v1.txt",
            "bus": "bus_data.csv",
        }[dataset]
        p = p / suffix

    if not p.exists():
        raise FileNotFoundError(f"Dataset path not found for {dataset}: {p}")

    normalized = p.as_posix()
    if "/data/" not in normalized and not normalized.startswith("data/"):
        raise ValueError(f"Dataset path must be under data/: {p}")
    return p


def _resolve_ground_truth_file(dataset: str, gt_path: str | None) -> Path:
    raw = gt_path or DEFAULT_GT_PATHS[dataset]
    p = Path(raw)
    if not p.is_absolute():
        p = (_repo_root / p).resolve()
    if not p.exists():
        raise FileNotFoundError(f"Ground-truth path not found for {dataset}: {p}")
    return p


def _safe_model_dirname(model: str) -> str:
    return model.replace("/", "__").replace(":", "_")


def _rows_for_judge(results: list[RunResult]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for r in results:
        if r.rejected and not r.executed:
            continue
        row = dataclasses.asdict(r)
        row["_source_file"] = "[in_memory_modeltype_run]"
        rows.append(row)
    return rows


def _run_single_query(
    query_text: str,
    sampled_df: pd.DataFrame,
    model: str,
    api_key: str,
) -> RunResult:
    client = LLMClient(model_name=model, api_key=api_key)
    runner = BaselineRunner(mode="FLASH_FUSION", df=sampled_df, client=client)
    try:
        return runner.run(query_text)
    except Exception as exc:
        r = RunResult(
            baseline="FLASH_FUSION",
            model=model,
            query=query_text,
            answer=f"[ERROR] {type(exc).__name__}: {exc}",
            executed=False,
            rejected=False,
        )
        r.input_tokens = client.total_input_tokens()
        r.output_tokens = client.total_output_tokens()
        r.cost_usd = client.total_cost_usd()
        return r


def _validate_models(models: list[str]) -> None:
    unknown = [m for m in models if m not in MODEL_RATE_PER_1M_TOKENS]
    if unknown:
        raise ValueError(
            "Unknown model(s): "
            f"{unknown}. Add rates in flashfusion/config.py or pass supported model IDs."
        )


def _make_run_id(explicit_run_id: str | None) -> str:
    if explicit_run_id:
        run_id = explicit_run_id.strip()
        if not run_id:
            raise ValueError("--run-id cannot be empty")
        return run_id
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def _resolve_run_output_dir(output_dir: str, run_id: str) -> Path:
    run_name = run_id if run_id.startswith("run_") else f"run_{run_id}"
    return Path(output_dir).resolve() / run_name


def _scaled_font_size(size: float) -> float:
    return size * FONT_SCALE


def _clean_axes(ax: Any) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


def _place_grouped_bar_labels(
    ax: Any,
    group_xpos: list[float],
    group_vals: list[float],
    group_stds: list[float],
    min_gap: float = 2.2,
    fontsize: float = 9.2,
) -> None:
    items: list[list[float]] = []
    for x, val, std in zip(group_xpos, group_vals, group_stds):
        if val <= 0:
            continue
        base_y = val + std + max(0.8, val * 0.012)
        items.append([x, val, base_y])

    items.sort(key=lambda t: t[2])
    for idx in range(1, len(items)):
        prev_y = items[idx - 1][2]
        items[idx][2] = max(items[idx][2], prev_y + min_gap)

    for x, val, y in items:
        ax.text(
            x,
            y,
            f"{val:.0f}%",
            ha="center",
            va="bottom",
            fontsize=_scaled_font_size(fontsize),
            fontweight="bold",
            clip_on=False,
        )


def _model_display_name(model: str) -> str:
    if "gemma-4-31b-it" in model:
        return "Gemma-4-31B"
    if "qwen-2.5-7b" in model:
        return "Qwen-2.5-7B"
    if "llama-3.3-70b" in model:
        return "Llama-3.3-70B"
    if "/" in model:
        return model.split("/", maxsplit=1)[1]
    return model


def _load_metrics_from_runs(base_output_dir: str) -> pd.DataFrame:
    """Load per-query metrics from all run_N folders.

    Scans the per-model subdirectory metrics.csv files
    (run_N/{dataset}/{model_dir}/metrics.csv) so that models added in separate
    --run-all passes are always included, even when the top-level
    metrics_vs_model_type.csv was overwritten by a later single-model pass.
    """
    base = Path(base_output_dir)
    if not base.exists():
        return pd.DataFrame()

    run_dirs = sorted(
        [d for d in base.iterdir() if d.is_dir() and d.name.startswith("run_")],
        key=lambda p: p.name,
    )
    if not run_dirs:
        return pd.DataFrame()

    frames: list[pd.DataFrame] = []
    for run_dir in run_dirs:
        run_frames: list[pd.DataFrame] = []
        # Scan run_N/{dataset}/{model_dir}/metrics.csv
        for dataset_dir in sorted(run_dir.iterdir()):
            if not dataset_dir.is_dir():
                continue
            for model_dir in sorted(dataset_dir.iterdir()):
                if not model_dir.is_dir():
                    continue
                csv_path = model_dir / "metrics.csv"
                if not csv_path.exists():
                    continue
                df = pd.read_csv(csv_path)
                if df.empty:
                    continue
                if "run_id" not in df.columns:
                    df["run_id"] = run_dir.name
                run_frames.append(df)

        if not run_frames:
            # Fall back to top-level aggregated CSV if no subdirectory files found.
            csv_path = run_dir / "metrics_vs_model_type.csv"
            if csv_path.exists():
                df = pd.read_csv(csv_path)
                if not df.empty:
                    if "run_id" not in df.columns:
                        df["run_id"] = run_dir.name
                    frames.append(df)
            continue

        run_df = pd.concat(run_frames, ignore_index=True)
        frames.append(run_df)

    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)


def _load_benchmark_ff_rows(
    benchmark_all_root: str,
    benchmark_ecg_root: str,
) -> pd.DataFrame:
    """Load Flash-Fusion rows from the llama-3.3-70b performance benchmark CSVs.

    Sources follow the same layout used by performance/measure.py:
      - bus, wisdm: <benchmark_all_root>/{dataset}/benchmark/metrics.csv
      - mit_ecg:    <benchmark_ecg_root>/benchmark/metrics.csv

    run_id values (1/2/3) are prefixed with 'bench_' to avoid collision with
    modeltype run_N folder names when summaries are merged for plotting.
    """
    def _resolve(p: str) -> Path:
        path = Path(p)
        if not path.is_absolute():
            path = (_repo_root / path).resolve()
        return path

    all_root = _resolve(benchmark_all_root)
    ecg_root = _resolve(benchmark_ecg_root)

    sources: list[tuple[str, Path]] = [
        ("bus",     all_root / "bus"   / "benchmark" / "metrics.csv"),
        ("wisdm",   all_root / "wisdm" / "benchmark" / "metrics.csv"),
        ("mit_ecg", ecg_root            / "benchmark" / "metrics.csv"),
    ]

    empty = pd.DataFrame(columns=["run_id", "dataset", "model_under_test", "gt_score"])
    frames: list[pd.DataFrame] = []
    for dataset, csv_path in sources:
        if not csv_path.exists():
            print(f"[benchmark] Skipping {dataset}: {csv_path} not found", flush=True)
            continue
        df = pd.read_csv(csv_path)
        mask = df["baseline"].str.strip().str.upper() == "FLASH_FUSION"
        df = df[mask].copy()
        if df.empty:
            continue
        df["dataset"] = dataset
        df["model_under_test"] = BENCHMARK_MODEL
        df["run_id"] = "bench_run_" + df["run_id"].astype(str)
        frames.append(df[["run_id", "dataset", "model_under_test", "gt_score"]])

    if not frames:
        return empty
    return pd.concat(frames, ignore_index=True)


def _aggregate_accuracy_across_runs(metrics_df: pd.DataFrame) -> pd.DataFrame:
    required = {"run_id", "dataset", "model_under_test", "gt_score"}
    missing = required - set(metrics_df.columns)
    if missing:
        raise ValueError(f"Missing required columns for aggregation: {sorted(missing)}")

    run_level = (
        metrics_df.groupby(["run_id", "dataset", "model_under_test"], as_index=False)
        .agg(avg_accuracy=("gt_score", "mean"))
        .sort_values(["run_id", "dataset", "model_under_test"])
    )

    combos_per_run = run_level.groupby("run_id").size()
    if not combos_per_run.empty and combos_per_run.nunique() != 1:
        raise ValueError(
            "Inconsistent dataset/model coverage across runs. "
            "All runs must contain the same dataset-model combinations."
        )

    summary = (
        run_level.groupby(["dataset", "model_under_test"], as_index=False)
        .agg(
            mean_accuracy=("avg_accuracy", "mean"),
            std_accuracy=("avg_accuracy", "std"),
            run_count=("avg_accuracy", "count"),
        )
        .sort_values(["dataset", "model_under_test"])
        .reset_index(drop=True)
    )
    summary["std_accuracy"] = summary["std_accuracy"].fillna(0.0)
    return summary


def run_experiment(
    datasets: list[str],
    models: list[str],
    query_ids: list[int] | None,
    data_paths: dict[str, str | None],
    gt_paths: dict[str, str | None],
    run_output_dir: str,
    judge_model: str,
    run_id: str,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    api_key = os.getenv("OPENROUTER_API_KEY") or os.getenv("GROQ_API_KEY")
    if not api_key:
        raise ValueError("OPENROUTER_API_KEY or GROQ_API_KEY environment variable required")

    os.makedirs(run_output_dir, exist_ok=True)
    all_metrics: list[pd.DataFrame] = []

    for dataset in datasets:
        data_file = _resolve_dataset_file(dataset, data_paths.get(dataset))
        gt_file = _resolve_ground_truth_file(dataset, gt_paths.get(dataset))
        gt_by_id = load_ground_truth(str(gt_file))
        query_defs = get_queries(dataset)
        valid_ids = {q["id"] for q in query_defs}
        query_map = {q["id"]: q["text"] for q in query_defs}

        if query_ids is None:
            active_ids = sorted(valid_ids)
        else:
            invalid = [qid for qid in query_ids if qid not in valid_ids]
            if invalid:
                raise ValueError(f"Invalid query IDs for {dataset}: {invalid}")
            active_ids = list(query_ids)

        print(f"[{dataset}] Loading dataset once: {data_file}", flush=True)
        df_full = load_dataset_by_name(str(data_file), dataset)
        if df_full.empty:
            raise ValueError(f"Dataset loaded empty for {dataset}: {data_file}")

        for model in models:
            print(f"[{dataset}] Model: {model}", flush=True)
            run_results: list[RunResult] = []

            for qid in active_ids:
                query_text = query_map[qid]
                print(f"[{dataset}] [{model}] Q{qid}: {query_text[:72]}...", flush=True)
                rr = _run_single_query(
                    query_text=query_text,
                    sampled_df=df_full,
                    model=model,
                    api_key=api_key,
                )
                run_results.append(rr)

            model_dir = os.path.join(run_output_dir, dataset, _safe_model_dirname(model))
            os.makedirs(model_dir, exist_ok=True)

            with open(os.path.join(model_dir, "raw_results.jsonl"), "w", encoding="utf-8") as fh:
                for r in run_results:
                    row = dataclasses.asdict(r)
                    row["dataset"] = dataset
                    fh.write(json.dumps(row, ensure_ascii=True) + "\n")

            rows = _rows_for_judge(run_results)
            judge_out = os.path.join(model_dir, "ground_truth_llm_judge")
            if rows:
                judgments_df, _, _ = run_llm_ground_truth_judge(
                    rows=rows,
                    ground_truth_by_id=gt_by_id,
                    output_dir=judge_out,
                    model_name=judge_model,
                    api_key=api_key,
                    data_path=str(data_file),
                    dataset=dataset,
                )
            else:
                judgments_df = pd.DataFrame()

            metrics_df = aggregate_metrics(
                run_results,
                llm_judgments_df=judgments_df,
                ground_truth_by_id=gt_by_id,
                query_defs=query_defs,
            )
            metrics_df["dataset"] = dataset
            metrics_df["model_under_test"] = model
            metrics_df["judge_model"] = judge_model
            metrics_df["run_id"] = run_id
            metrics_df["data_path"] = str(data_file)
            metrics_df["ground_truth_path"] = str(gt_file)
            metrics_df.to_csv(os.path.join(model_dir, "metrics.csv"), index=False)
            all_metrics.append(metrics_df)

    if all_metrics:
        query_metrics_df = pd.concat(all_metrics, ignore_index=True)
    else:
        query_metrics_df = pd.DataFrame()

    summary_df = (
        query_metrics_df.groupby(["dataset", "model_under_test", "judge_model"], as_index=False)
        .agg(
            avg_accuracy=("gt_score", "mean"),
            avg_latency_s=("latency_s", "mean"),
            avg_cost_usd=("cost_usd", "mean"),
            execution_rate=("executed", "mean"),
            query_count=("query_id", "count"),
        )
        .sort_values(["dataset", "model_under_test"])
        .reset_index(drop=True)
    )

    query_metrics_df.to_csv(os.path.join(run_output_dir, "metrics_vs_model_type.csv"), index=False)
    summary_df.to_csv(os.path.join(run_output_dir, "modeltype_summary.csv"), index=False)

    with open(os.path.join(run_output_dir, "run_metadata.json"), "w", encoding="utf-8") as fh:
        json.dump(
            {
                "run_id": run_id,
                "datasets": datasets,
                "models": models,
                "judge_model": judge_model,
                "query_ids": query_ids,
            },
            fh,
            ensure_ascii=True,
            indent=2,
        )

    return query_metrics_df, summary_df


def plot_results_from_runs(
    base_output_dir: str,
    benchmark_all_root: str | None = None,
    benchmark_ecg_root: str | None = None,
) -> None:
    """Aggregate cross-run data from modeltype run_N folders plus 70B benchmark data and plot."""
    _empty_summary = pd.DataFrame(
        columns=["dataset", "model_under_test", "mean_accuracy", "std_accuracy", "run_count"]
    )

    # Small-model data from modeltype run_N folders (may not exist yet).
    small_model_df = _load_metrics_from_runs(base_output_dir)
    if not small_model_df.empty:
        small_summary = _aggregate_accuracy_across_runs(small_model_df)
    else:
        small_summary = _empty_summary.copy()

    # 70B Flash-Fusion data from performance benchmark CSVs (3 genuine runs).
    eff_all_root = benchmark_all_root or DEFAULT_BENCHMARK_ALL_ROOT
    eff_ecg_root = benchmark_ecg_root or DEFAULT_BENCHMARK_ECG_ROOT
    bench_df = _load_benchmark_ff_rows(eff_all_root, eff_ecg_root)
    if not bench_df.empty:
        bench_summary = _aggregate_accuracy_across_runs(bench_df)
    else:
        bench_summary = _empty_summary.copy()

    non_empty = [df for df in [small_summary, bench_summary] if not df.empty]
    summary_df = pd.concat(non_empty, ignore_index=True) if non_empty else _empty_summary.copy()

    if summary_df.empty:
        print("No cross-run summary data to plot.")
        return

    out_dir = Path(base_output_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    summary_csv = out_dir / "modeltype_summary_across_runs.csv"
    summary_df.to_csv(summary_csv, index=False)

    plt.rcParams.update(PLOT_RC)
    datasets = [d for d in DATASET_ORDER if d in set(summary_df["dataset"])]
    # Order bars by MODEL_PLOT_ORDER (ascending model size), fall back to data order.
    present = set(summary_df["model_under_test"])
    models = [m for m in MODEL_PLOT_ORDER if m in present]
    if not models:
        models = list(summary_df["model_under_test"].unique())

    x = list(range(len(datasets)))
    width = 0.8 / max(len(models), 1)

    fig, ax = plt.subplots(figsize=(7.0, 3.6))
    group_positions = {ds: [] for ds in datasets}
    group_means = {ds: [] for ds in datasets}
    group_stds = {ds: [] for ds in datasets}

    colors = ["#2f8f57", "#4c78a8", "#f58518", "#b279a2"]
    for idx, model in enumerate(models):
        subset = summary_df[summary_df["model_under_test"] == model]
        means_pct: list[float] = []
        stds_pct: list[float] = []
        for ds in datasets:
            hit = subset[subset["dataset"] == ds]
            mean_val = float(hit["mean_accuracy"].iloc[0]) if not hit.empty else 0.0
            std_val = float(hit["std_accuracy"].iloc[0]) if not hit.empty else 0.0
            means_pct.append(mean_val * 100.0)
            stds_pct.append(std_val * 100.0)

        xpos = [p - 0.4 + (idx + 0.5) * width for p in x]
        ax.bar(
            xpos,
            means_pct,
            width,
            label=_model_display_name(model),
            color=colors[idx % len(colors)],
            edgecolor="#333333",
            linewidth=0.6,
            yerr=stds_pct,
            error_kw={"elinewidth": 1.0, "capsize": 3, "ecolor": "#222222"},
        )

        for ds, xp, mean_val, std_val in zip(datasets, xpos, means_pct, stds_pct):
            group_positions[ds].append(xp)
            group_means[ds].append(mean_val)
            group_stds[ds].append(std_val)

    for ds in datasets:
        _place_grouped_bar_labels(
            ax,
            group_positions[ds],
            group_means[ds],
            group_stds[ds],
            min_gap=2.4,
            fontsize=9.2,
        )

    ax.set_xticks(x)
    ax.set_xticklabels([DATASET_LABELS.get(ds, ds) for ds in datasets])
    ax.set_ylabel("Query Accuracy (%)")
    ax.set_ylim(0, 115)
    ax.yaxis.grid(linestyle="--", alpha=0.35)
    ax.set_axisbelow(True)
    _clean_axes(ax)

    ax.legend(
        ncol=max(1, len(models)),
        mode="expand",
        loc="upper center",
        bbox_to_anchor=(-0.03, -0.21, 1.06, 0.1),
        borderaxespad=0.0,
        frameon=False,
        fontsize=_scaled_font_size(10),
        columnspacing=5.0,
        handlelength=1.8,
        handletextpad=0.6,
        labelspacing=2.0,
        title=None,
    )

    fig.tight_layout()
    out_png = out_dir / "fig_accuracy_by_dataset_modeltype.png"
    out_pdf = out_dir / "fig_accuracy_by_dataset_modeltype.pdf"
    fig.savefig(out_png, dpi=200, bbox_inches="tight")
    fig.savefig(out_pdf, dpi=200, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved cross-run summary CSV: {summary_csv}")
    print(f"Saved plot to {out_png}")
    print(f"Saved plot to {out_pdf}")


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Flash-Fusion model-size comparison with benchmark-style GT scoring.",
    )
    parser.add_argument(
        "--datasets",
        nargs="+",
        default=list(SUPPORTED_DATASETS),
        choices=list(SUPPORTED_DATASETS),
        help="Datasets to evaluate (default: wisdm mit_ecg bus)",
    )
    parser.add_argument(
        "--query-ids",
        nargs="+",
        type=int,
        default=None,
        help="Optional query IDs subset. Default is all dataset queries (Q1-Q12).",
    )
    parser.add_argument(
        "--models",
        nargs="+",
        default=None,
        help="Models under test. Default is the two smaller models.",
    )
    parser.add_argument(
        "--judge-model",
        default=DEFAULT_JUDGE_MODEL,
        help=(
            "Model used by the ground-truth LLM judge "
            f"(default: {DEFAULT_JUDGE_MODEL})"
        ),
    )
    parser.add_argument(
        "--run-id",
        default=None,
        help="Optional run id suffix. If omitted, uses current timestamp.",
    )
    parser.add_argument("--wisdm-data", default=None, help="Override WISDM data file/dir")
    parser.add_argument("--mit-ecg-data", default=None, help="Override MIT ECG data file/dir")
    parser.add_argument("--bus-data", default=None, help="Override bus data file/dir")
    parser.add_argument("--wisdm-gt", default=None, help="Override WISDM ground-truth JSON")
    parser.add_argument("--mit-ecg-gt", default=None, help="Override MIT ECG ground-truth JSON")
    parser.add_argument("--bus-gt", default=None, help="Override bus ground-truth JSON")
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR, help="Output directory")
    parser.add_argument(
        "--benchmark-data-root",
        default=None,
        help=(
            "Root dir for bus/wisdm benchmark data from performance/measure.py "
            f"(default: {DEFAULT_BENCHMARK_ALL_ROOT})"
        ),
    )
    parser.add_argument(
        "--benchmark-ecg-root",
        default=None,
        help=(
            "Root dir for ECG Flash-Fusion benchmark data from performance/measure.py "
            f"(default: {DEFAULT_BENCHMARK_ECG_ROOT})"
        ),
    )
    parser.add_argument("--plot", action="store_true", help="Generate summary plot")
    parser.add_argument(
        "--run-all",
        action="store_true",
        help="Run all 3 runs sequentially (run_id 1/2/3) then generate the summary figure.",
    )
    parser.add_argument(
        "--dry-run-check-paths",
        action="store_true",
        help="Validate models/paths/ground-truth files and exit",
    )
    parser.add_argument(
        "--plot-only",
        action="store_true",
        help="Skip running experiments; only aggregate run_* outputs and plot.",
    )
    return parser


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()

    datasets = list(dict.fromkeys(args.datasets))
    models = args.models or list(DEFAULT_SMALL_MODELS)

    _validate_models(models)
    _validate_models([args.judge_model])

    data_paths: dict[str, str | None] = {
        "wisdm": args.wisdm_data,
        "mit_ecg": args.mit_ecg_data,
        "bus": args.bus_data,
    }
    gt_paths: dict[str, str | None] = {
        "wisdm": args.wisdm_gt,
        "mit_ecg": args.mit_ecg_gt,
        "bus": args.bus_gt,
    }

    run_id = _make_run_id(args.run_id)
    run_output_dir = _resolve_run_output_dir(args.output_dir, run_id)

    if args.dry_run_check_paths:
        print("Preflight checks")
        print(f"  Run id: {run_id}")
        print(f"  Run output directory: {run_output_dir}")
        print(f"  Models under test: {models}")
        print(f"  Judge model: {args.judge_model}")
        for dataset in datasets:
            ds_path = _resolve_dataset_file(dataset, data_paths.get(dataset))
            gt_path = _resolve_ground_truth_file(dataset, gt_paths.get(dataset))
            print(f"  {dataset}: data={ds_path}")
            print(f"  {dataset}: gt={gt_path}")
        print("Dry-run preflight complete.")
        return

    if args.plot_only:
        plot_results_from_runs(
            args.output_dir,
            benchmark_all_root=args.benchmark_data_root,
            benchmark_ecg_root=args.benchmark_ecg_root,
        )
        return

    if args.run_all:
        for run_num in (1, 2, 3):
            run_id_n = str(run_num)
            run_output_dir_n = _resolve_run_output_dir(args.output_dir, run_id_n)
            print(f"\n{'='*60}", flush=True)
            print(f"Starting run {run_num}/3  →  {run_output_dir_n}", flush=True)
            print(f"{'='*60}", flush=True)
            q_df, s_df = run_experiment(
                datasets=datasets,
                models=models,
                query_ids=args.query_ids,
                data_paths=data_paths,
                gt_paths=gt_paths,
                run_output_dir=str(run_output_dir_n),
                judge_model=args.judge_model,
                run_id=run_output_dir_n.name,
            )
            print(f"Run {run_num} complete — {len(q_df)} query rows, {len(s_df)} summary rows.", flush=True)
        print("\nAll 3 runs complete. Generating figure…", flush=True)
        plot_results_from_runs(
            args.output_dir,
            benchmark_all_root=args.benchmark_data_root,
            benchmark_ecg_root=args.benchmark_ecg_root,
        )
        return

    query_metrics_df, summary_df = run_experiment(
        datasets=datasets,
        models=models,
        query_ids=args.query_ids,
        data_paths=data_paths,
        gt_paths=gt_paths,
        run_output_dir=str(run_output_dir),
        judge_model=args.judge_model,
        run_id=run_output_dir.name,
    )

    print(f"Saved per-query rows: {len(query_metrics_df)}")
    print(f"Saved summary rows: {len(summary_df)}")
    print(f"Run output directory: {run_output_dir}")
    print(f"Summary CSV: {run_output_dir / 'modeltype_summary.csv'}")

    if args.plot:
        plot_results_from_runs(
            args.output_dir,
            benchmark_all_root=args.benchmark_data_root,
            benchmark_ecg_root=args.benchmark_ecg_root,
        )


if __name__ == "__main__":
    main()